---
- name: Configure MSO Policies
  hosts: mso
  gather_facts: false
    
  tasks:

  - name: Loading "NDO EPGs Static Ports" Information from CSV File
    read_csv:
      path: ../aci_config/mso_staticport.csv
    register: mso_staticport
    delegate_to: localhost
    tags:
     - staticport

  - name: Configure Static Port to Endpoint Group
    cisco.mso.mso_schema_site_anp_epg_staticport:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: false
      schema: "{{ item.schema_name }}"
      site: "{{ item.site_name }}"
      template: "{{ item.template_name }}"
      anp: "{{ item.anp_name }}"
      epg: "{{ item.epg_name }}"
      type: "{{ item.deploy_type }}"
      pod: "{{ item.pod }}"
      leaf: "{{ item.leaf }}"
      path: "{{ item.path }}"
      vlan: "{{ item.vlan }}"
      mode: "{{ item.vlan_mode }}"
      deployment_immediacy: immediate
      state: present
    loop: "{{ mso_staticport.list }}"
    loop_control:
      label: "Creating Static Ports for \"{{ item.leaf }}\" + \"{{ item.path }}\" on EPG \"{{ item.epg_name }}\""
    tags:
     - staticport



#  - name: Deploy Configuration
#    cisco.mso.mso_schema_template_deploy:
#      hostname: "{{ ansible_host }}"
#      username: "{{ ansible_user }}"
#      password: "{{ ansible_password }}"
#      validate_certs: false
#      schema: "{{ item.schema_name }}"
#      template: "{{ item.template_name }}"
#      state: deploy
#    loop: "{{ mso_tn_objects.list | json_query('[].{schema_name: schema_name, template_name: template_name}') | unique  }}"
#    loop_control:
#      label: "Deploying Configuration for \"{{ item.schema_name }}\" and Template \"{{ item.template_name }}\""
#    tags:
#     - bd